version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: traffic-fine-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-init:/docker-entrypoint-initdb.d
    networks:
      - traffic-network

volumes:
  mysql-data:

networks:
  traffic-network:
    driver: bridge
